apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: utils
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  -
    {{- if ne .Values.host "*" }}
    host: "{{ .Values.host }}"
    {{- end }}
    http:
      paths:
      - backend:
          service:
            name: adminer
            port:
              number: 80
        path: /_adminer
        pathType: Prefix

      - backend:
          service:
            name: rediscommander
            port:
              number: 80
        path: /_redis
        pathType: Prefix

      - backend:
          service:
            name: phpmyadmin-caddy
            port:
              number: 80
        path: /_phpmyadmin
        pathType: Prefix

      - backend:
          service:
            name: whoami
            port:
              number: 80
        path: /_whoami
        pathType: Prefix
