apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: phpmyadmin-{{ .Release.Name }}
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:5.1
          ports:
            - containerPort: 80
          env:
            - name: PMA_ARBITRARY
              value: "1"
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "64Mi"
