---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin-{{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
