apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitmweb-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mitmweb-{{ .Release.Name }}
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: mitmweb
          image: mitmproxy/mitmproxy
          command:
            - mitmweb
            - --web-host
            - 0.0.0.0
{{- if .Values.allowGlobalIps }}
            - --set
            - block_global=false
{{- end }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "64Mi"
