---
apiVersion: v1
kind: Service
metadata:
  name: mitmproxy
spec:
  selector:
    app: mitmweb-{{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mitmweb
spec:
  selector:
    app: mitmweb-{{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
