apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: adminer-{{ .Release.Name }}
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: adminer
          image: thecodingmachine/php:7.4-v4-cli
          command: ["/usr/bin/php", "-S[::]:5000", "-t", "/usr/src/app"]
          ports:
            - containerPort: 5000
          env:
            - name: PHP_EXTENSIONS
              value: mongodb
          lifecycle:
           postStart:
             exec:
               command: [ "wget", "-O/usr/src/app/index.php", "https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-pl.php" ]
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "64Mi"
