---
apiVersion: v1
kind: Service
metadata:
  name: adminer-{{ .Release.Name }}
spec:
  selector:
    app: adminer-{{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
