---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-gui
spec:
  selector:
    app: mongodb-gui-{{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
